BASE="$HOME/dotfiles/zsh"
export PATH="$(yarn global bin):$PATH"
source $BASE/aliases.zsh
unsetopt correct_all
export EDITOR='nvim'
alias tmux="tmux -2"
source $BASE/zplug.zsh
source $BASE/extras.zsh
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
export FZF_DEFAULT_COMMAND='(git ls-tree -r --name-only HEAD ||
   find * -name ".*" -prune -o -type f -print -o -type l -print) 2> /dev/null'
export ENHANCD_FILTER="fzf"
. $HOME/.asdf/asdf.sh

eval "$(pyenv init -)"
